version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: jam_db
    environment:
      POSTGRES_USER: jam_user
      POSTGRES_PASSWORD: jam_password
      POSTGRES_DB: jam_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
